### ISSUE TITLE
Scrap Customization/Bugs

### ISSUE THREAD

**Issue by tungstenmeteor** [Windows10CE/ScrapChests#1]
Main issues are:

Bugs:
- Regular Multishops still spawn with triple scrap
- Green-Multishops drop white scrap instead of green
- Equipment multishops have the equipments replaced with white scrap
- Void Fields enemies gain scrap instead of items between levels

Config/Customization Needs:
- Legendary scrap is not able to be cashed in at the legendary newt bazaar lunar pool
- Legendary scrap is extremely hard to cash in due to legendary printers being extremely rare (control likelihood rates of printer spawns)

Being able to customize these things would be very helpful. This is possibly the most enjoyable artifact/modifier I've played with but the bugs and limiters make it just shy of greatness. Fixes eagerly requested!

**Comment by Windows10CE** [comment]
I'm really sorry for being late on this, I'm not very used to checking repos for issues :p. But thanks a lot for the report! I was pretty sure I had solved the void fields issue with an earlier update, but I'll make sure to do a bit of extra testing. If you could join the modding discord (https://discord.gg/U8FGRMUfnr) and give me a mention that would be fantastic, I'd love to be able to talk and get a bit more information about some of the bugs you're encountering.

**Comment by Windows10CE** [comment]
- [x] Regular multishops cost the same as normal chests, and as a personal thing, I see it is kind of funny, so it's a bit of a non-issue that can be solved using other mods if you really wanted to.
- [x] Confirmed green multishops drop white scrap, I believe it's due to the itemTier variable I reference not actually being changed based on the tier of multishop. Should be a pretty easy fix as long as I find something else to check.
- [x] Equipment multishops is the same issue as above, there's no variable identifying that a multishop is for equipment in the multishop class. Should also be a pretty easy fix?
- [ ] Sadly I wasn't able to reproduce the void fields issue on my own. Can you check if you're running the latest version of the mod? Should be version 3.2.0.

As for the config options you talked about, I could certainly include the first one here, but the second one feels like it'd be better to include in a mod exclusively about changing the spawn weights and costs of different interactables. I don't know off the top of my head whether or not a mod that does that exists, but I'm currently working on a mod that would allow you do that as well as several other customizations.

Anyway, I'll be fixing those two multishop bugs tonight, there should be a release up in a bit.

**Comment by Windows10CE** [comment]
Just released a fix, thanks again for the report!
