### ISSUE TITLE
SivsItems causes Shrines of Chance to drop items

### ISSUE THREAD

**Issue by MightyW0lf** [Windows10CE/ScrapChests#2]
Mod SivsItems (0.0.6, by Sivelos1) causes Shrines of Chance to drop regular items instead of scrap. [A video showing the bug.](https://youtu.be/rskqNSWFA3k)

Mods:
* bbepis-BepInExPack-5.3.1
* tristanmcpherson-R2API-2.5.14
* **Windows10CE-ScrapChests-3.2.1**
* Harb-DebugToolkit-3.4.2
* **Silvelos1-SivsItems-0.0.6**

**Comment by Windows10CE** [comment]
Thanks a lot for the report! After doing a bit of testing, I found that the issue is actually caused by any mod that uses a specific feature of R2API called ItemDropAPI. After messing with it a bit, I found a way to bypass what R2API does to the chance shrines to allow for ScrapChests to function correctly again. I'll have a new release up that fixes the issue in a bit.

**Comment by Windows10CE** [comment]
Just made the release, thanks a lot!

**Comment by MightyW0lf** [comment]
Seems like the fix causes a new issue: Shrines of Chance now break after not dropping an item once. Video demonstration [here](https://youtu.be/Hr3VGcjHPyk) (notice that the shrine doesn't even send a message in the chat when rolling no item). Mods are the same, tested with ScrapChests v3.2.2.

**Comment by Windows10CE** [comment]
I got this once or twice in testing, but it had seemed to go away after a bit more development, so I had assumed I fixed the issue with something else I implemented. I'll look through it a bit more and see what's going on.

**Comment by Windows10CE** [comment]
Made another release to solve the issue, just had to add a few extra checks.
